name: UNISA Monitor

# Esegui ogni ora (cron in UTC). Lo script decide se fare il controllo in base all'ora Europa/Rome.
on:
  schedule:
    - cron: '0 * * * *'   # ogni ora esatta
  workflow_dispatch: {}   # permette di eseguirlo manualmente da GitHub Actions UI

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor_unisa.py

      - name: Commit hashes.json if changed
        run: |
          git add hashes.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update monitor state [ci skip]" || echo "commit fallito"
            git push || echo "push fallito"
          fi
